import React from "react";

const Blogpost: React.FC = () => {
  return (
    <div id="blogpost-1770114455805">
    <div id="iywri" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="i5djg" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="i1qfl" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"MOLA"}</h2>
        <div id="idznk" style={{"display": "inline", "flexDirection": "column", "flex": "1", "alignContent": "stretch", "float": "left", "position": "relative", "--chart-color-palette": "default"}}>
          <a id="ibvtf" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/home">{"Home"}</a>
        </div>
        <p id="iyv5h" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "20px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"This page is 80% generated by BESSER and 20% by AI (exact numbers)"}</p>
      </nav>
      <main id="ilol1" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="ixhmi" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"Blog Post 1"}</h1>
        <img id="i2vbc" style={{"color": "black", "--chart-color-palette": "default"}} src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+" alt="Image component" />
        <p id="i122o" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"This is the textual content of the blog post"}</p>
        <div id="i16jfi" style={{"marginTop": "20px", "display": "flex", "gap": "10px", "flexWrap": "wrap", "--chart-color-palette": "default"}} />
        <section id="i9ftp" style={{"padding": "60px 0", "background": "#f5f5f5", "--chart-color-palette": "default"}} />
        <section id="i2w15" style={{"padding": "60px 0", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
          <div id="izsx3v" style={{"maxWidth": "1200px", "margin": "0 auto", "padding": "0 20px", "--chart-color-palette": "default"}}>
            <h2 id="ihmq2f">{"Comments"}</h2>
            <button id="i4ti8b" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} {...{"type": "button"}}>{"Button"}</button>
            <section id="ijpstj" style={{"padding": "60px 0", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
              <div id="i4o2d4" style={{"maxWidth": "1200px", "margin": "0 auto", "padding": "0 20px", "--chart-color-palette": "default"}}>
                <h2 id="iro57o">{"Comment 1"}</h2>
                <p id="i6xkz3">{"Author"}</p>
                <p id="i8lvs6">{"Content"}</p>
              </div>
            </section>
          </div>
        </section>
      </main>
    </div>    </div>
  );
};

export default Blogpost;
